# coding: utf-8

"""
    MOPC Events API

    This API provides interface for CRUD operations with various events

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from events_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="MOPC Events API",
    description="This API provides interface for CRUD operations with various events",
    version="0.1",
)

app.include_router(DefaultApiRouter)
